spring.application.name=hospital-management
spring.datasource.url=jdbc:mysql://localhost:3306/hospital
spring.datasource.username=root
spring.datasource.password=Student@13022007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
